---
language: ruby
cache: bundler
rvm:
  - 2.5.0
before_install: gem install bundler -v 2.1.4
matrix:
  fast_finish: true
script:
- sh script/travis.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master